// Generates src/styles/tokens.css from src/tokens/index.ts.
// Run via `pnpm gen:tokens`. CI asserts no diff.
//
// Breakpoints are deliberately NOT generated into any stylesheet — see the
// note on `breakpoints` in src/tokens/index.ts.
//
// Output is piped through Prettier before writing so the generated file
// always matches `pnpm format:check` — without this, any token value long
// enough to trigger Prettier's CSS line-wrapping would drift from its
// committed, formatted state on every regeneration.
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import * as prettier from 'prettier'
import {
  color,
  colorDark,
  control,
  weight,
  spacing,
  motion,
  zIndex,
  font,
  layout,
} from '../src/tokens/index.ts'

const root = resolve(import.meta.dirname, '..')
const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())
const lines = []
const push = (name, value) => lines.push(`  --fnb-${name}: ${value};`)

lines.push('/* GENERATED by scripts/gen-tokens.mjs — do not edit by hand. */')
lines.push(':root {')

lines.push('  /* Colors */')
for (const [k, v] of Object.entries(color)) push(kebab(k), v)

lines.push('')
lines.push('  /* Derived. Overriding --fnb-brand re-derives these. */')
push('brand-hover', 'color-mix(in oklab, var(--fnb-brand), #fff 17%)')
push('shadow-color', 'var(--fnb-border)')

lines.push('')
lines.push('  /* Fonts */')
for (const [k, v] of Object.entries(font)) push(`font-${k}`, v)

lines.push('')
lines.push(
  '  /* Zero radius is intrinsic to this design language — one variable,'
)
lines.push(
  '     not a scale: there is no size/weight dimension for corners. */'
)
push('radius', '0')

lines.push('')
lines.push('  /* Dimension one: size. Bare names default to md. */')
for (const [k, v] of Object.entries(control.md)) push(`control-${k}`, v)
for (const [size, vals] of Object.entries(control))
  for (const [k, v] of Object.entries(vals)) push(`control-${k}-${size}`, v)

lines.push('')
lines.push('  /* Dimension two: weight. Bare names default to w3. */')
for (const [k, v] of Object.entries(weight.w3)) push(`weight-${k}`, v)
for (const [w, vals] of Object.entries(weight))
  for (const [k, v] of Object.entries(vals)) push(`${w}-${k}`, v)

lines.push('')
lines.push('  /* Spacing, motion, stacking, layout */')
for (const [k, v] of Object.entries(spacing)) push(`space-${k}`, v)
for (const [k, v] of Object.entries(motion)) push(kebab(k), v)
for (const [k, v] of Object.entries(zIndex)) push(`z-${kebab(k)}`, v)
for (const [k, v] of Object.entries(layout)) push(kebab(k), v)

lines.push('}')
lines.push('')
lines.push('.dark {')
for (const [k, v] of Object.entries(colorDark)) push(kebab(k), v)
lines.push(
  '  /* Keep the hard shadow visible on dark ground; derives from brand */'
)
push('shadow-color', 'color-mix(in oklab, var(--fnb-brand), #000 27%)')
lines.push('}')
lines.push('')

async function writeFormatted(relPath, content) {
  const filepath = resolve(root, relPath)
  const config = (await prettier.resolveConfig(filepath)) ?? {}
  const formatted = await prettier.format(content, { ...config, filepath })
  writeFileSync(filepath, formatted)
}

await writeFormatted('src/styles/tokens.css', lines.join('\n'))

console.log('gen-tokens OK')
