// Generates src/styles/tokens.css and src/styles/_breakpoints.scss from
// src/tokens/index.ts. Run via `pnpm gen:tokens`. CI asserts no diff.
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  color,
  colorDark,
  control,
  weight,
  spacing,
  motion,
  zIndex,
  font,
  layout,
  breakpoints,
} from '../src/tokens/index.ts'

const root = resolve(import.meta.dirname, '..')
const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())
const lines = []
const push = (name, value) => lines.push(`  --fnb-${name}: ${value};`)

lines.push('/* GENERATED by scripts/gen-tokens.mjs — do not edit by hand. */')
lines.push(':root {')

lines.push('  /* Colors */')
for (const [k, v] of Object.entries(color)) push(kebab(k), v)

lines.push('')
lines.push('  /* Derived. Overriding --fnb-brand re-derives these. */')
push('brand-hover', 'color-mix(in oklab, var(--fnb-brand), #fff 17%)')
push('shadow-color', 'var(--fnb-border)')

lines.push('')
lines.push('  /* Fonts */')
for (const [k, v] of Object.entries(font)) push(`font-${k}`, v)

lines.push('')
lines.push('  /* Zero radius is intrinsic to this design language — one variable,')
lines.push('     not a scale: there is no size/weight dimension for corners. */')
push('radius', '0')

lines.push('')
lines.push('  /* Dimension one: size. Bare names default to md. */')
for (const [k, v] of Object.entries(control.md)) push(`control-${k}`, v)
for (const [size, vals] of Object.entries(control))
  for (const [k, v] of Object.entries(vals)) push(`control-${k}-${size}`, v)

lines.push('')
lines.push('  /* Dimension two: weight. Bare names default to w3. */')
for (const [k, v] of Object.entries(weight.w3)) push(`weight-${k}`, v)
for (const [w, vals] of Object.entries(weight))
  for (const [k, v] of Object.entries(vals)) push(`${w}-${k}`, v)

lines.push('')
lines.push('  /* Spacing, motion, stacking, layout */')
for (const [k, v] of Object.entries(spacing)) push(`space-${k}`, v)
for (const [k, v] of Object.entries(motion)) push(kebab(k), v)
for (const [k, v] of Object.entries(zIndex)) push(`z-${kebab(k)}`, v)
for (const [k, v] of Object.entries(layout)) push(kebab(k), v)

lines.push('}')
lines.push('')
lines.push('.dark {')
for (const [k, v] of Object.entries(colorDark)) push(kebab(k), v)
lines.push('  /* Keep the hard shadow visible on dark ground; derives from brand */')
push('shadow-color', 'color-mix(in oklab, var(--fnb-brand), #000 27%)')
lines.push('}')
lines.push('')

writeFileSync(resolve(root, 'src/styles/tokens.css'), lines.join('\n'))

const scss = [
  '// GENERATED by scripts/gen-tokens.mjs — do not edit by hand.',
  '// CSS variables do not work inside @media conditions; use these instead.',
  ...Object.entries(breakpoints).map(([k, v]) => `$fnb-bp-${k}: ${v}px;`),
  '',
].join('\n')
writeFileSync(resolve(root, 'src/styles/_breakpoints.scss'), scss)

console.log('gen-tokens OK')
